run-small:
	./build/install/app-shadow/bin/app /mnt/2TB/inc/Download/ip_addresses/small

run-small-debug:
	./build/install/app-shadow/bin/app -d /mnt/2TB/inc/Download/ip_addresses/small

run-default:
	./build/install/app-shadow/bin/app

run-large-debug:
	./build/install/app-shadow/bin/app -d /mnt/2TB/inc/Download/ip_addresses/ip_addresses

build:
	./gradlew clean installShadowDist

.PHONY: build